const CHIP_COLORS = ['#d62728','#1f77b4','#2ca02c','#ff7f0e','#9467bd','#17becf','#8c564b','#e377c2','#bcbd22','#7f7f7f'];
const FALLBACK_TICKERS = [['SPY','SPDR S&P 500'],['AAPL','Apple Inc.'],['MSFT','Microsoft Corp.'],['GOOG','Alphabet Inc.'],['AMZN','Amazon.com Inc.'],['TSLA','Tesla, Inc.'],['NVDA','NVIDIA Corp.'],['JPM','JPMorgan Chase & Co.'],['BAC','Bank of America Corp.'],['DIS','Walt Disney Co.'],['NFLX','Netflix, Inc.']].map(([symbol,name]) => ({symbol,name}));
let tickerCatalogPromise;
function loadTickerCatalog(){
  if(tickerCatalogPromise) return tickerCatalogPromise;
  tickerCatalogPromise = fetch('data/tickers.csv').then((response) => { if(!response.ok) throw new Error('tickers.csv unavailable'); return response.text(); }).then((text) => text.split(/\r?\n/).filter(Boolean).filter((line,index) => index || !line.toLowerCase().startsWith('symbol')).map((line) => { const comma = line.indexOf(','); return comma < 0 ? {symbol: line.trim(), name: ''} : {symbol: line.slice(0,comma).replace(/^"|"$/g,'').trim(), name: line.slice(comma + 1).replace(/^"|"$/g,'').trim()}; }).filter((item) => item.symbol)).catch(() => FALLBACK_TICKERS);
  return tickerCatalogPromise;
}

class PlotCard {
  constructor(config){
    this.config = config;
    this.selectedTickers = [...config.symbols];
    this.element = document.createElement('article');
    this.element.className = 'plot-card card';
    this.element.dataset.plotId = config.id;
    this.element.innerHTML = `<div class="plot-heading"><input class="plot-title" type="text" placeholder="Enter plot title"><select class="plot-type" aria-label="Plot type"><option value="timeseries">Timeseries</option><option value="histogram">Histogram</option><option value="treemap">Treemap</option></select><select class="y-value" aria-label="Y value"><option value="open">Open</option><option value="high">High</option><option value="low">Low</option><option value="close" selected>Close</option><option value="volume">Volume</option><option value="market_value">Market Value</option></select></div><div class="plot-controls controls"><div class="controls-row controls-row-tickers"><div class="ticker-group"><label>Ticker:</label><div class="selected-tickers" aria-live="polite"></div></div></div><div class="controls-row controls-row-fields"><span class="combo"><div class="search-box"><input class="ticker-input" type="text" autocomplete="off" aria-haspopup="listbox" aria-expanded="false" placeholder="Search tickers..."><button class="dropdown-toggle" type="button" aria-label="Show suggestions">▾</button></div><ul class="suggestions" role="listbox" hidden></ul></span><label>Start: <input class="plot-start" type="date"></label><label>End: <input class="plot-end" type="date"></label><button class="execute tab" type="button">Execute Query</button><div class="plot-status" role="status"></div></div></div><div class="histogram-controls" hidden><label>Date range: <span class="histogram-range-label"></span></label><div class="histogram-slider"><input class="histogram-range-start" type="range" min="0" max="100" value="0"><input class="histogram-range-end" type="range" min="0" max="100" value="100"></div></div><div class="plot-output"></div>`;
    this.title = this.element.querySelector('.plot-title'); this.plotType = this.element.querySelector('.plot-type'); this.yValue = this.element.querySelector('.y-value'); this.input = this.element.querySelector('.ticker-input'); this.suggestions = this.element.querySelector('.suggestions'); this.selected = this.element.querySelector('.selected-tickers'); this.status = this.element.querySelector('.plot-status'); this.histogramControls = this.element.querySelector('.histogram-controls'); this.rangeStart = this.element.querySelector('.histogram-range-start'); this.rangeEnd = this.element.querySelector('.histogram-range-end'); this.rangeLabel = this.element.querySelector('.histogram-range-label');
    this.title.value = config.title; this.yValue.value = config.yValue || 'close'; this.element.querySelector('.plot-start').value = config.start; this.element.querySelector('.plot-end').value = config.end; this.updateHistogramRange(); this.renderSelected(); this.bindEvents(); loadTickerCatalog();
  }
  color(symbol){ return CHIP_COLORS[symbol.split('').reduce((sum,char) => sum + char.charCodeAt(0),0) % CHIP_COLORS.length]; }
  renderSelected(){
    this.selected.innerHTML = ''; this.selected.hidden = !this.selectedTickers.length;
    this.selectedTickers.forEach((symbol) => { const chip = document.createElement('button'); const color = this.color(symbol); chip.type='button'; chip.className='selected-ticker-chip'; chip.textContent=symbol; chip.title=`Remove ${symbol}`; chip.style.borderColor=color; chip.style.color=color; chip.style.background=`${color}20`; chip.onclick=() => { this.selectedTickers=this.selectedTickers.filter((item) => item !== symbol); this.renderSelected(); this.showSuggestions(''); }; this.selected.appendChild(chip); });
  }
  positionSuggestions(){ const rect = this.input.getBoundingClientRect(); const width = `${rect.width}px`; this.suggestions.style.left=`${rect.left}px`; this.suggestions.style.top=`${rect.bottom + 6}px`; this.suggestions.style.width=width; this.suggestions.style.minWidth=width; this.suggestions.style.maxWidth=width; }
  async showSuggestions(filter){
    const catalog = await loadTickerCatalog(); const query = filter.trim().toUpperCase(); const selected = this.selectedTickers.map((symbol) => symbol.toUpperCase()); const matches = catalog.filter((item) => !query || item.symbol.toUpperCase().includes(query) || item.name.toUpperCase().includes(query)); this.suggestions.innerHTML='';
    matches.sort((a,b) => Number(!selected.includes(a.symbol.toUpperCase())) - Number(!selected.includes(b.symbol.toUpperCase()))).forEach((item) => { const option=document.createElement('li'); option.tabIndex=0; option.dataset.symbol=item.symbol; option.textContent=`${item.symbol} — ${item.name}`; if(selected.includes(item.symbol.toUpperCase())) option.style.fontWeight='700'; this.suggestions.appendChild(option); });
    this.suggestions.hidden = !matches.length; if(matches.length){ this.suggestions.style.display='block'; this.positionSuggestions(); this.input.setAttribute('aria-expanded','true'); }
  }
  closeSuggestions(){ this.suggestions.hidden=true; this.suggestions.style.display='none'; this.input.setAttribute('aria-expanded','false'); }
  addTicker(symbol){ const normalized=symbol.toUpperCase(); this.selectedTickers=this.selectedTickers.includes(normalized) ? this.selectedTickers.filter((item) => item !== normalized) : [normalized,...this.selectedTickers]; this.input.value=''; this.renderSelected(); this.showSuggestions(''); this.input.focus(); }
  updateHistogramRange(){
    const start = this.element.querySelector('.plot-start').value; const end = this.element.querySelector('.plot-end').value;
    this.histogramControls.hidden = !['histogram', 'treemap'].includes(this.plotType.value);
    this.rangeLabel.textContent = `${this.sliderDate(this.rangeStart.value)} to ${this.sliderDate(this.rangeEnd.value)}`;
    if(!start || !end) return;
    this.rangeStart.setAttribute('aria-label', `Histogram start date ${this.sliderDate(this.rangeStart.value)}`); this.rangeEnd.setAttribute('aria-label', `Histogram end date ${this.sliderDate(this.rangeEnd.value)}`);
  }
  sliderDate(value){
    const start = new Date(`${this.element.querySelector('.plot-start').value}T00:00:00`); const end = new Date(`${this.element.querySelector('.plot-end').value}T00:00:00`); const days = Math.max(0, Math.round((end - start) / 86400000)); const date = new Date(start.getTime() + (days * Number(value) / 100) * 86400000); return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0,10);
  }
  histogramDates(){ const start = this.sliderDate(this.rangeStart.value); const end = this.sliderDate(this.rangeEnd.value); return start <= end ? {start, end} : {start: end, end: start}; }
  renderHistogram(series){
    const width = 1100; const height = 570; const padding = {top: 48, right: 300, bottom: 92, left: 78}; const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.style.maxWidth = '100%'; canvas.setAttribute('aria-label', 'Histogram of closing prices');
    const context = canvas.getContext('2d'); context.clearRect(0, 0, width, height); const dates = this.histogramDates(); const visible = series.map((item) => ({...item, points: item.points.filter((point) => point.date >= dates.start && point.date <= dates.end)})); const allPrices = series.flatMap((item) => item.points.map((point) => point.value));
    if(!allPrices.length){ this.element.querySelector('.plot-output').replaceChildren(canvas); return; }
    const min = Math.floor(Math.min(...allPrices) / 10) * 10; const max = Math.ceil(Math.max(...allPrices) / 10) * 10; const binCount = 30; const step = (max - min || 10) / binCount; const chartWidth = width - padding.left - padding.right; const chartHeight = height - padding.top - padding.bottom; const chartBottom = height - padding.bottom; const counts = visible.map((item) => Array(binCount).fill(0)); let peak = 0;
    visible.forEach((item, seriesIndex) => item.points.forEach((point) => { const index = Math.min(binCount - 1, Math.floor((point.value - min) / step)); counts[seriesIndex][index] += 1; }));
    peak = Math.max(...counts.flat(), 1);
    const renderOrder = counts.map((seriesCounts, seriesIndex) => ({seriesCounts, seriesIndex})).sort((a, b) => Math.max(...b.seriesCounts) - Math.max(...a.seriesCounts));
    context.font = '12px Courier New'; context.fillStyle = '#000'; context.strokeStyle = '#000'; context.lineWidth = 1;
    for(let tick = 0; tick <= 5; tick += 1){ const y = chartBottom - (tick / 5) * chartHeight; context.strokeStyle = '#d0d0d0'; context.beginPath(); context.moveTo(padding.left, y); context.lineTo(width - padding.right, y); context.stroke(); context.fillStyle = '#000'; context.textAlign = 'right'; context.fillText(String(Math.round((tick / 5) * peak)), padding.left - 8, y + 4); }
    context.strokeStyle = '#000'; context.beginPath(); context.moveTo(padding.left, padding.top); context.lineTo(padding.left, chartBottom); context.lineTo(width - padding.right, chartBottom); context.stroke();
    const colors = ['#d62728','#1f77b4','#2ca02c','#ff7f0e','#9467bd','#17becf','#8c564b','#e377c2','#bcbd22','#7f7f7f']; const barWidth = chartWidth / binCount;
    renderOrder.forEach(({seriesCounts, seriesIndex}) => { context.fillStyle = colors[seriesIndex % colors.length]; seriesCounts.forEach((count, index) => { const barHeight = peak ? (count / peak) * chartHeight : 0; context.globalAlpha = 0.55; context.fillRect(padding.left + index * barWidth, height - padding.bottom - barHeight, barWidth + 1, barHeight); }); }); context.globalAlpha = 1;
    renderOrder.forEach(({seriesCounts, seriesIndex}) => { const points = seriesCounts.map((count, index) => ({x: padding.left + (index + 0.5) * barWidth, y: chartBottom - (peak ? count / peak : 0) * chartHeight})); context.strokeStyle = colors[seriesIndex % colors.length]; context.lineWidth = 2.5; context.beginPath(); context.moveTo(points[0].x, points[0].y); for(let index = 0; index < points.length - 1; index += 1){ const current = points[index]; const next = points[index + 1]; const midpoint = {x: (current.x + next.x) / 2, y: (current.y + next.y) / 2}; context.quadraticCurveTo(current.x, current.y, midpoint.x, midpoint.y); } const last = points[points.length - 1]; context.quadraticCurveTo(last.x, last.y, last.x, last.y); context.stroke(); });
    context.fillStyle = '#000'; context.textAlign = 'center'; for(let tick = 0; tick <= binCount; tick += 1){ const x = padding.left + tick * barWidth; const value = min + tick * step; context.strokeStyle = '#000'; context.beginPath(); context.moveTo(x, chartBottom); context.lineTo(x, chartBottom + 5); context.stroke(); if(tick % 5 === 0 || tick === binCount) context.fillText(Math.round(value / 10) * 10, x, chartBottom + 20); }
    context.fillText('Price', padding.left + chartWidth / 2, height - 47); context.fillText(`${dates.start} to ${dates.end}`, padding.left + chartWidth / 2, height - 25); context.save(); context.translate(18, padding.top + chartHeight / 2); context.rotate(-Math.PI / 2); context.fillText('Frequency', 0, 0); context.restore();
    context.textAlign = 'left'; visible.forEach((item, index) => { const x = width - padding.right + 18; const y = padding.top + index * 24; context.fillStyle = colors[index % colors.length]; context.fillRect(x, y - 10, 12, 12); context.fillStyle = '#000'; context.fillText(`${item.symbol}: ${item.name}`, x + 18, y); }); this.element.querySelector('.plot-output').replaceChildren(canvas);
  }
  renderTreemap(series){
    const width = 1100; const height = 500; const padding = 18; const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.style.maxWidth = '100%'; canvas.setAttribute('aria-label', 'Treemap of average closing prices'); const context = canvas.getContext('2d'); context.font = '14px Courier New';
    const dates = this.histogramDates(); const values = series.map((item, index) => { const points = item.points.filter((point) => point.date >= dates.start && point.date <= dates.end); const value = points.length ? points.reduce((total, point) => total + point.value, 0) / points.length : 0; return {item, value, index}; }).filter((entry) => entry.value > 0).sort((a, b) => b.value - a.value); const total = values.reduce((sum, entry) => sum + entry.value, 0) || 1; let x = padding; let y = padding; let rowHeight = 0; const gap = 4; const colors = ['#d62728','#1f77b4','#2ca02c','#ff7f0e','#9467bd','#17becf','#8c564b','#e377c2','#bcbd22','#7f7f7f'];
    context.fillStyle = '#fff'; context.fillRect(0, 0, width, height); values.forEach((entry) => { const area = (entry.value / total) * (width - padding * 2) * (height - padding * 2); const tileWidth = Math.max(90, Math.sqrt(area)); if(x + tileWidth > width - padding){ x = padding; y += rowHeight + gap; rowHeight = 0; } const tileHeight = Math.max(70, area / tileWidth); context.fillStyle = colors[entry.index % colors.length]; context.globalAlpha = 0.82; context.fillRect(x, y, Math.min(tileWidth, width - padding - x), Math.min(tileHeight, height - padding - y)); context.globalAlpha = 1; context.fillStyle = '#000'; context.fillText(entry.item.symbol, x + 8, y + 24); context.font = '11px Courier New'; context.fillText(entry.item.name.slice(0, 26), x + 8, y + 42); context.fillText(`Avg $${entry.value.toFixed(2)}`, x + 8, y + 58); context.font = '14px Courier New'; x += tileWidth + gap; rowHeight = Math.max(rowHeight, tileHeight); }); this.element.querySelector('.plot-output').replaceChildren(canvas);
  }
  bindEvents(){
    this.input.oninput=() => this.showSuggestions(this.input.value); this.input.onclick=() => this.showSuggestions(this.input.value); this.element.querySelector('.dropdown-toggle').onclick=() => this.suggestions.hidden ? this.showSuggestions('') : this.closeSuggestions(); this.suggestions.onclick=(event) => { const option=event.target.closest('li'); if(option) this.addTicker(option.dataset.symbol); };
    this.input.onkeydown=(event) => { if(event.key==='ArrowDown'){ event.preventDefault(); this.showSuggestions(this.input.value).then(() => this.suggestions.querySelector('li')?.focus()); } };
    this.suggestions.onkeydown=(event) => { const current=document.activeElement; const options=[...this.suggestions.querySelectorAll('li')]; const index=options.indexOf(current); if(event.key==='ArrowDown'||event.key==='ArrowUp'){ event.preventDefault(); options[(index + (event.key==='ArrowDown' ? 1 : options.length - 1)) % options.length]?.focus(); } else if(event.key==='Enter'){ event.preventDefault(); if(current?.dataset.symbol) this.addTicker(current.dataset.symbol); } else if(event.key==='Escape'){ this.closeSuggestions(); this.input.focus(); } };
    this.plotType.onchange=() => this.updateHistogramRange(); this.yValue.onchange=() => { if(this.histogramData) this.plotType.value === 'treemap' ? this.renderTreemap(this.histogramData) : this.renderHistogram(this.histogramData); }; this.element.querySelector('.plot-start').onchange=() => { this.updateHistogramRange(); if(['histogram', 'treemap'].includes(this.plotType.value)) this.histogramData = null; }; this.element.querySelector('.plot-end').onchange=() => { this.updateHistogramRange(); if(['histogram', 'treemap'].includes(this.plotType.value)) this.histogramData = null; }; [this.rangeStart, this.rangeEnd].forEach((range) => range.oninput=() => { if(Number(this.rangeStart.value) > Number(this.rangeEnd.value)){ const value = range === this.rangeStart ? this.rangeEnd.value : this.rangeStart.value; range.value = value; } this.updateHistogramRange(); if(this.histogramData) this.plotType.value === 'treemap' ? this.renderTreemap(this.histogramData) : this.renderHistogram(this.histogramData); });
    this.element.querySelector('.execute').onclick=() => this.execute(); document.addEventListener('click',(event) => { if(!this.element.contains(event.target) && !this.suggestions.contains(event.target)) this.closeSuggestions(); }); window.addEventListener('resize',() => { if(!this.suggestions.hidden) this.positionSuggestions(); }); window.addEventListener('scroll',() => { if(!this.suggestions.hidden) this.positionSuggestions(); });
  }
  async execute(){
    const start=this.element.querySelector('.plot-start').value; const end=this.element.querySelector('.plot-end').value; if(!this.selectedTickers.length||!start||!end){ this.status.textContent='Select ticker and dates'; return; } this.status.textContent='Running...'; const startedAt=performance.now();
    const plotDates = this.plotType.value === 'histogram' ? {start, end} : {start, end};
    try{ const response=await fetch('http://localhost:5000/api/plot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:this.selectedTickers,start:plotDates.start,end:plotDates.end,title:this.title.value.trim()||this.config.title,plot_type:this.plotType.value,y_value:this.yValue.value,data_only:['histogram', 'treemap'].includes(this.plotType.value)}),cache:'no-store'}); if(!response.ok){ const error=await response.json().catch(() => null); this.status.textContent=error?.error||`Error: ${response.status}`; return; } if(['histogram', 'treemap'].includes(this.plotType.value)){ const data=await response.json(); this.histogramData=data.series; this.plotType.value === 'treemap' ? this.renderTreemap(this.histogramData) : this.renderHistogram(this.histogramData); const elapsedSeconds=((performance.now()-startedAt)/1000).toFixed(2); this.status.textContent=`Done (${data.series.reduce((total, item) => total + item.points.length, 0)} points, ${elapsedSeconds} seconds)`; return; } const blob=await response.blob(); if(this.imageUrl) URL.revokeObjectURL(this.imageUrl); this.imageUrl=URL.createObjectURL(blob); const image=document.createElement('img'); image.src=this.imageUrl; image.alt=`${this.selectedTickers.join(', ')} plot`; image.style.maxWidth='100%'; this.element.querySelector('.plot-output').replaceChildren(image); const elapsedSeconds=((performance.now()-startedAt)/1000).toFixed(2); this.status.textContent=`Done (${blob.size} bytes, ${elapsedSeconds} seconds)`; }catch(error){ console.error(error); this.status.textContent='Error'; }
  }
}